### PR TITLE
DL3-82 Limit the use of the loading screen in the Content Selector an

### PR DESCRIPTION
**Pull request by mpellicer**
## Description
Only display the loading screen when a course or modules have been selected, when courses are being loaded display a simple spinner like the previous version.

### Motivation and Context
The loading screen should only be displayed when a course is being paired, not when courses are being loaded.

### Fixes
[Jira ticket](https://lumenlearning.atlassian.net/browse/DL3-82)

## How Has This Been Tested?
Tested locally simulating the scenarios. Tested against D2L using the DEV environment.

## Screenshots

image

---

## New ENV variables

---

## Checklist

- [X] I have reviewed the AC for this feature and my changes meet all requirements
- [X] (For UI changes) I have considered the accessibility of this feature (see https://www.a11yproject.com/checklist/ for a high-level checklist)
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have requested a review from at least one other dev

### CODE REVIEW

**Comment by mpellicer** [comment]
This has to be merged after #77 because there's a dependency.

**Review by mgwozdz-unicon — APPROVED** [review]
Looks good

**Review by HotchkissLuLe — APPROVED** [review]
This looks great! Thanks Miguel

**Review by smith750 — APPROVED** [review]
Looks good to me - thank you!

**Review by leannethng — APPROVED** [review]

**Comment by mpellicer** [comment]
Thanks for the reviews!

**Pull request merged**
