### PR TITLE
DL3-45 Display an error when the configured root_outcome_guid does not match any Harmony course

### PR DESCRIPTION
**Pull request by mpellicer**
## Description
Shows an error when the Middleware provides a configured root_outcome_guid that does not match with any Harmony current course.

Displays the selected course when the backend sends to the frontend a previous root_outcome_guid.

### Motivation and Context
The user can pair an LMS course with a Harmony course, then the Middleware will send to the frontend the root_outcome_guid , this value can be invalid if the course does not exist in the Harmony endpoint anymore.

### Fixes
[Jira ticket](https://lumenlearning.atlassian.net/browse/DL3-45)

## How Has This Been Tested?
This has been tested locally simulating all the possible combinations. 

## Screenshots

When the previously selected course exists displays it.
DL3-45

When the previously selected course does not exist displays an error:
DL3-45-2

---

## New ENV variables

---

## Checklist

- [X] I have reviewed the AC for this feature and my changes meet all requirements
- [X] (For UI changes) I have considered the accessibility of this feature (see https://www.a11yproject.com/checklist/ for a high-level checklist)
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have requested a review from at least one other dev.

### CODE REVIEW

**Comment by mgwozdz-unicon** [comment]
When I test this with my code from DL3-75, the course catalog page actually flashes on my screen for a brief second before displaying the course preview page for my paired course. Is this something that you would be able to fix?

**Comment by mpellicer** [comment]
> When I test this with my code from DL3-75, the course catalog page actually flashes on my screen for a brief second before displaying the course preview page for my paired course. Is this something that you would be able to fix?

Hi @mgwozdz-unicon, you're right, it displays the list of courses, then moves to the course, I've fixed the case.

Miguel

**Comment by mpellicer** [comment]
Marked as ready for review.

**Review by mgwozdz-unicon — APPROVED** [review]
This looks great! Thanks Miguel!

**Review by smith750 — APPROVED** [review]
This looks great to me!

**Review by HotchkissLuLe — APPROVED** [review]
Looks awesome, thanks for the comments

**Review by leannethng — APPROVED** [review]
This looks great thanks!

**Pull request merged**
