### PR TITLE
DL3-74 sync lineitems for returning DL users and add local mock valkyrie

### PR DESCRIPTION
**Pull request by mgwozdz-unicon**
## Description
Lineitems are fetched from the LMS to be synced to Valkyrie on every launch (both standard LtiResourceLink launches and Deep Linking launches) except when the database indicates that the lineitems have already been synced. Upon receiving a root_outcome_guid from the lineitems sync for a course that doesn't already have one associated to it, I save the root_outcome_guid to the course and send it to the front end deep linking menu. I also set up INFO level logging for this feature and set the logging level for the AWS envs to INFO by default. Additionally, I added a MockValkyrieController to allow for local testing of the full integration flows.

### Motivation and Context
This allows us to match the root_outcome_guid on Deep Linking launches so that in the case where a course has been copied, the course catalog can be hidden from the instructor.

### Fixes
[DL3-74](https://lumenlearning.atlassian.net/browse/DL3-74)

## How Has This Been Tested?
On this [Google Sheet](https://docs.google.com/spreadsheets/d/1J3lMo5hHEwK3b05fS2Oc29Yz_w2PRyBqttlXas1cYZg/edit?usp=sharing), I outlined all of the possible use cases for the first three launches in an original and in a copied course. Then I eliminated the ones that were effectively duplicates, and eight cases remained, which are highlighted in blue. I went through each of these cases while following along in the logs and the database to ensure that the behavior matched what was expected.

## Screenshots
N/A

---

## Database changes
N/A

## ⚠️ Deployment instructions ⚠️
N/A

## New ENV variables
N/A

---

## Checklist
- [x] I have reviewed the AC for this feature and my changes meet all requirements
- [ ] (For UI changes) I have considered the accessibility of this feature (see https://www.a11yproject.com/checklist/ for a high-level checklist)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have requested a review from at least one other dev

### CODE REVIEW

**Review by HotchkissLuLe — APPROVED** [review]
This looks great Mary! Thank you for the helpful comments in LTI3Controller :)

**Review by smith750 — APPROVED** [review]
Looks great!

**Review by leannethng — APPROVED** [review]
Thanks so much Mary! This looks great to me and I appreciate you adding in the spreadsheet of cases that was super helpful!

**Review by mpellicer — APPROVED** [review]

**Comment by mpellicer** [comment]
Thanks!

**Pull request merged**
