### PR TITLE
DL3-58 - Waiting Screens while Deep Links are Added to the LMS Course

### PR DESCRIPTION
**Pull request by mpellicer**
## Description
When some actions are performed we should display a loading page, this page is shown when the frontend is loading courses from the Harmony, and is also shown when a a course has been selected and the user adds the course or content to the LMS.

### Motivation and Context
Improves the behavior when the app is loading data.

### Fixes
[Jira ticket](https://lumenlearning.atlassian.net/browse/DL3-58)

## How Has This Been Tested?
I has been tested locally simulating the conditions and also tested using D2L and reproducing the entire workflow, when a user did not select any course, loading courses, navigating across pages and adding deep links to the LMS.

## Screenshots
There's two videos, one syncing an entire course and another one adding some modules, also combined with the error when adding deep links.

DL3-58-OK

DL3-58-KO

---

## New ENV variables

---

## Checklist

- [X] I have reviewed the AC for this feature and my changes meet all requirements
- [X] (For UI changes) I have considered the accessibility of this feature (see https://www.a11yproject.com/checklist/ for a high-level checklist)
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have requested a review from at least one other dev

### CODE REVIEW

**Review by mgwozdz-unicon — CHANGES_REQUESTED** [review]
Could you please change the color of the "Group illustrations by Storyset" to be gray instead of blue so that it matches the design? Or is it blue for accessibility reasons?

**Review by smith750 — APPROVED** [review]
This looks good - thank you!

**Review by HotchkissLuLe — APPROVED** [review]
This looks great!

**Comment by mpellicer** [comment]
> Could you please change the color of the "Group illustrations by Storyset" to be gray instead of blue so that it matches the design? Or is it blue for accessibility reasons?

Thanks! My bad. Axe does not report anything about the link color, complains about the loading text.

**Pull request merged**
