### PR TITLE
DL3-14 React UI: Update the data model to the Waymaker schema.

### PR DESCRIPTION
**Pull request by mpellicer**
DL3-13 incorporates an endpoint to retrieve the books from Waymaker with an specific schema, this PR updates the objects and the components to use the same schema.

## Description

- Replaces the static data object using the new schema.
- Updates the components to use the same attributes.
- Formats the release date.

### Motivation and Context
The previous schema was done for mocking purposes, this is the valid schema.

### Fixes
[Jira ticket](https://lumenlearning.atlassian.net/browse/DL3-14)

## How Has This Been Tested?

- Accessibility using Axe.
- Search input finding courses by book title.
- List courses.
- Access the course preview.
- Re-test the navigation.

## Screenshots

image
image
image
image

## Checklist

- [X] I have reviewed the AC for this feature and my changes meet all requirements
- [X] (For UI changes) I have considered the accessibility of this feature (see https://www.a11yproject.com/checklist/ for a high-level checklist)
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have requested a review from at least one other dev

### CODE REVIEW

**Comment by mpellicer** [comment]
@smith750 @mgwozdz-unicon @leannethng 

Unfortunately, I can't add you as reviewers in this PR, would you mind reviewing this work? Thank you so much

**Review by mgwozdz-unicon — APPROVED** [review]
Looks great, thanks Miguel!

**Review by smith750 — APPROVED** [review]
Looks good - thanks for all these updates.

**Comment by mpellicer** [comment]
@smith750 Could we merge this? Thanks!

**Comment by smith750** [comment]
As soon as @HotchkissLuLe  has approved, yes, you can merge this.  Thank you!

**Review by HotchkissLuLe — APPROVED** [review]
This all looks great to me. I wonder, is the time desired in the release date display? Nothing that can't be changed at a later date if not

**Comment by mpellicer** [comment]
Thanks for the reviews, I'm asking to merge it because I don't have permissions to merge it!

Thanks again.

**Pull request merged**
