### PR TITLE
Dl3 97 do not sync lineitems if deep linking disabled

### PR DESCRIPTION
**Pull request by mgwozdz-unicon**
## Description
I updated the middleware to not try to sync the lineitems if deep linking is disabled. I also added INFO logging to indicate that this is happening (please let me know if this is overkill for logging - it will be very easy to remove).

### Motivation and Context
This ensures that there aren't errors when doing standard LTI core launches with deep linking disabled and no harmony API in place.

### Fixes
[DL3-97](https://lumenlearning.atlassian.net/browse/DL3-97)

## How Has This Been Tested?
1. Ensured that deep linking is enabled locally.
2. In a new course in the LMS that has access to my local tool, I went through the deep linking flow and inserted the links to my test course.
3. I clicked on one of the links I had inserted and ensured that the logs indicated that the lineitems syncing had taken place.
```
2022-09-22 16:18:12.479  INFO 18118 --- [-nio-443-exec-5] n.u.lti.controller.lti.LTI3Controller    : 23 lineitems have been synced to Harmony successfully for iss https://unicon.d2l-partners.brightspace.com, client_id 68ff69cc-7bb6-46c4-b899-31af213713e1, deployment_id b97f0815-d874-44c3-82d2-09beb0d66c05, and LMS context_id 6997. We received root_outcome_guid 357365c8-fd91-415b-8139-aa19779dabdd from Harmony.
```
4. I disabled Deep Linking in my local environment and redeployed.
5. I returned to the same course and clicked on one of the link and ensured that there were no errors in the logs and that there was no indication that lineitems had synced.
```
2022-09-22 16:20:56.912  INFO 18733 --- [-nio-443-exec-5] n.u.lti.controller.lti.LTI3Controller    : Lineitems will not be synced because deep linking is disabled.
```

## Screenshots
N/A

---
## Database changes
N/A

## ⚠️ Deployment instructions ⚠️
N/A

## New ENV variables
N/A

---

## Checklist
- [x] I have reviewed the AC for this feature and my changes meet all requirements
- [ ] (For UI changes) I have considered the accessibility of this feature (see https://www.a11yproject.com/checklist/ for a high-level checklist)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have requested a review from at least one other dev

### CODE REVIEW

**Review by smith750 — APPROVED** [review]
Looks great - thank you so so much for the quick turnaround on this

**Comment by mgwozdz-unicon** [comment]
I realized that it was also a bug that the system wasn't completely broken due to the absence of the harmony API url, so I just updated this PR to fix that issue as well. Now if deep linking is enabled, there must be a value for the harmony API url or else the Lumen error page displays. If deep linking is disabled, then no value is required for the harmony API url and lineitems syncing does not take place.

**Review by HotchkissLuLe — APPROVED** [review]
This looks great to me, Mary. I don't have any opinions on the amount of logging, but others might

**Review by leannethng — APPROVED** [review]
Thanks so much Mary, this looks great to me!

**Review by smith750 — APPROVED** [review]
This looks great - thank you!

**Pull request merged**
