### PR TITLE
DL3-56 Display error message if LINEITEMs aren't successfully synced to Harmony

### PR DESCRIPTION
**Pull request by mpellicer**
## Description
When there's an error syncing line items the frontend must display an error.

### Motivation and Context
Provides an error message when there's an error syncing line items

### Fixes
[Jira ticket](https://lumenlearning.atlassian.net/browse/DL3-56)

## How Has This Been Tested?

Tested locally simulating the scenarios and tested against D2L.

## Screenshots
DL3-56
DL3-56

---

## New ENV variables

---

## Checklist

- [X] I have reviewed the AC for this feature and my changes meet all requirements
- [X] (For UI changes) I have considered the accessibility of this feature (see https://www.a11yproject.com/checklist/ for a high-level checklist)
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have requested a review from at least one other dev

### CODE REVIEW

**Comment by mpellicer** [comment]
This needs rebasing after #79

**Review by mgwozdz-unicon — CHANGES_REQUESTED** [review]
This looks good, but could you please remove the breadcrumbs from the error page?

**Comment by mpellicer** [comment]
This is how it looks like after the change:
image

**Review by mgwozdz-unicon — APPROVED** [review]
Thanks Miguel! Looks great!

**Comment by mpellicer** [comment]
Thanks for the review @mgwozdz-unicon !

**Pull request merged**
