### PR TITLE
DL3-76 Returning User workflow- bread crumb and Cancel button improvements

### PR DESCRIPTION
**Pull request by mpellicer**
## Description
When a course has been paired with the LMS and the user wants to add modules, it should skip the course catalog page. This PR also removes the breadcrumb and the cancel button so the user cannot select a different course.

### Motivation and Context
It will prevent the user to cancel or go to the course catalog using the breadcrumb links.

### Fixes
[Jira ticket](https://lumenlearning.atlassian.net/browse/DL3-76)

## How Has This Been Tested?
Tested locally simulating the conditions and tested using D2L with a previously associated course.

## Screenshots
In the following video the user access a linked course, displays the course preview and the breadcrumb and the cancel buttons are not present.

DL3-76

---

## New ENV variables

---

## Checklist

- [X] I have reviewed the AC for this feature and my changes meet all requirements
- [X] (For UI changes) I have considered the accessibility of this feature (see https://www.a11yproject.com/checklist/ for a high-level checklist)
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have requested a review from at least one other dev

### CODE REVIEW

**Comment by mpellicer** [comment]
This needs to be merged after #69 rebasing.

**Comment by mpellicer** [comment]
> I think Sarah said that she wanted to keep the white bar and just remove the breadcrumb text. Could you please put the white bar back?

Of course, before the additional commit:
image

After the additional commit:
image

**Review by leannethng — APPROVED** [review]
Thanks, this looks great!

**Review by mgwozdz-unicon — APPROVED** [review]
Thanks for the quick fix!

**Review by smith750 — APPROVED** [review]
Looks good to me!

**Pull request merged**
