### PR TITLE
DL3-38 Update some alert messages to match the style guide.

### PR DESCRIPTION
**Pull request by mpellicer**
Update some alert messages to match the style guide.

Some messages require text updates and some styling changes to match the designs of the style guide https://www.figma.com/file/gxMNkfdJjFP8PbSpqtWZfA/Exemplar-Style-Guide?node-id=2412%3A1256

## Description
Improve the error messages and the styling.

### Motivation and Context
Matches the error messages with the required messages and the style guide.

### Fixes
[Jira ticket](https://lumenlearning.atlassian.net/browse/DL-38)

## How Has This Been Tested?
Comparing the previous messages with the new ones.

## Screenshots
image

image

---

## New ENV variables

---

## Checklist

- [X] I have reviewed the AC for this feature and my changes meet all requirements
- [X] (For UI changes) I have considered the accessibility of this feature (see https://www.a11yproject.com/checklist/ for a high-level checklist)
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules
- [X] I have updated the documentation accordingly.
- [X] I have requested a review from at least one other dev

### CODE REVIEW

**Review by mgwozdz-unicon — CHANGES_REQUESTED** [review]
When the error message loads for me, it looks like it's stuck in a left-hand column. Could you please fix this so that it displays across the page?

image

**Comment by mpellicer** [comment]
> When the error message loads for me, it looks like it's stuck in a left-hand column. Could you please fix this so that it displays across the page?
> 
> image

Of course, makes sense to me. I'll update and rebase all of this work, was done before firehole was merged.

**Comment by mpellicer** [comment]
Now the error message displays the full page.

image

**Comment by mpellicer** [comment]
I've also adjusted other messages:

image

**Pull request merged**
